server:
  port: 8003

spring:
  application:
    name: USERS-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update


